name: Go CI  # CI 流程的名称

on:  # 触发条件
  push:
    branches: [ main, master ]  # 推送到 main 或 master 分支时触发
  pull_request:
    branches: [ main, master ]  # 针对这些分支创建 PR 时也触发

jobs:
  test:  # 定义一个名为 test 的任务
    name: Run Tests and Lint
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 系统上运行
    
    steps:  # 定义执行步骤
    # 步骤 1: 获取代码
    - name: Checkout code
      uses: actions/checkout@v4

    # 步骤 2: 设置 Go 环境
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.0'  # 指定 Go 版本
        cache: true  # 启用缓存，加速后续构建

    # 步骤 3: 下载依赖
    - name: Download dependencies
      run: go mod download

    # 步骤 4: 运行测试
    - name: Run tests
      run: go test -v -race ./...

    # 步骤 5: 构建项目
    - name: Build
      run: go build -v ./...

    # 步骤 6: 代码检查 (可选但推荐)
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.55